name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: customer-management-system
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      DATABASE_UN: ${{ secrets.DATABASE_UN }}
      DATABASE_PW: ${{ secrets.DATABASE_PW }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Run the unit tests
        run: mvn test

      - name: Build and push the image
        run: |
          docker login --username bindudokala --password ${{secrets.CUSTOMER_ACCESS_TOKEN}} ghcr.io
          docker build -t ghcr.io/bindudokala/customer-app:$VERSION --file Dockerfile .  
          docker push ghcr.io/bindudokala/customer-app:$VERSION

      - name: Setup kubectl
        uses: azure/setup-kubectl@v3

      - name: Set KUBECONFIG
        run: |
          echo "${{ secrets.KUBE_CONFIG_DATA }}" | base64 -d > kubeconfig
          export KUBECONFIG=$PWD/kubeconfig

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f deployment.yaml
